#!/bin/bash
mv -n /config.json /etc/woodevops-toolkit/config.json

ORIGINAL_PHP_INI='/etc/php/8.1/fpm/php.ini'
CUSTOM_PHP_INI='/etc/woodevops-toolkit/custom_files/php.ini'

if [ -f "$CUSTOM_PHP_INI" ]; then
    sudo cp "$ORIGINAL_PHP_INI" "$CUSTOM_PHP_INI" 
    echo 'Custom php.ini copied successfully.'
else
    echo 'Custom php.ini not found. Not copied.'
fi

ORIGINAL_NGINX_CONF='/etc/nginx/nginx.conf'
CUSTOM_NGINX_CONF='/etc/woodevops-toolkit/custom_files/nginx.conf'

if [ -f "$CUSTOM_NGINX_CONF" ]; then
    sudo cp "$ORIGINAL_NGINX_CONF" "$CUSTOM_NGINX_CONF"
    echo 'Custom nginx.conf copied successfully.'
else
    echo 'Custom nginx.conf not found. Not copied.'
fi

sudo php /etc/woodevops-toolkit/scripts/update_phpini.php
sudo php /etc/woodevops-toolkit/scripts/create_nginx_config_files.php
