#!/bin/bash
mkdir -p /etc/woodevops-toolkit

if [ -d "/etc/woodevops-toolkit/custom_files" ]; then 
    mv -n /custom_files/* /etc/woodevops-toolkit/custom_files
else
    mv /custom_files /etc/woodevops-toolkit
fi

if [ -d "/etc/woodevops-toolkit/scripts" ]; then rm -Rf /etc/woodevops-toolkit/scripts; fi
if [ -d "/etc/woodevops-toolkit/pages" ]; then rm -Rf /etc/woodevops-toolkit/pages; fi

mv /scripts /etc/woodevops-toolkit
mv /pages /etc/woodevops-toolkit
mv -n /config.json /etc/woodevops-toolkit/config.json

ORIGINAL_PHP_INI='/etc/php/8.1/fpm/php.ini'
CUSTOM_PHP_INI='/etc/woodevops-toolkit/custom_files/php.ini'

if [ -f "$CUSTOM_PHP_INI" ]; then
    cp "$CUSTOM_PHP_INI" "$ORIGINAL_PHP_INI"
    echo 'Custom php.ini copied successfully.'
else
    echo 'Custom php.ini not found. Not copied.'
fi

ORIGINAL_NGINX_CONF='/etc/nginx/nginx.conf'
CUSTOM_NGINX_CONF='/etc/woodevops-toolkit/custom_files/nginx.conf'

if [ -f "$CUSTOM_NGINX_CONF" ]; then
    cp "$CUSTOM_NGINX_CONF" "$ORIGINAL_NGINX_CONF"
    echo 'Custom nginx.conf copied successfully.'
else
    echo 'Custom nginx.conf not found. Not copied.'
fi

php /etc/woodevops-toolkit/scripts/update_phpini.php
php /etc/woodevops-toolkit/scripts/create_nginx_config_files.php