name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: docker build -t create_package_image -f createPackage.Dockerfile .

      - name: Run Docker Container
        run: docker run create_package_image

      - name: Copy folders to Docker container
        run: |
          docker cp DEBIAN create_package_image:/project
          docker cp custom_files create_package_image:/project
          docker cp scripts create_package_image:/project

      - name: Create .deb Package
        run: |
          docker run -v ${{ github.workspace }}:/project create_package_image bash -c "cd /project && dpkg-deb --build package"

      - name: Retrieve .deb Package
        run: |
          mv ${{ github.workspace }}/*.deb ${{ github.workspace }}

      - name: Upload .deb Package
        uses: actions/upload-artifact@v4
        with:
          name: deb-package
          path: ${{ github.workspace }}/*.deb