name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        run: docker build -t create_package_image -f createPackage.Dockerfile .

      - name: Run Docker Container
        run: docker run -it create_package_image

      - name: Create .deb Package
        run: |
          docker run -v ${{ github.workspace }}:/project create_package_image bash -c "cd /project && dpkg-buildpackage -us -uc"

      - name: Retrieve .deb Package
        run: |
          mv ${{ github.workspace }}/*.deb ${{ github.workspace }}

      - name: Upload .deb Package
        uses: actions/upload-artifact@v2
        with:
          name: deb-package
          path: ${{ github.workspace }}/*.deb