name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: List Files
        run: |
          ls -la ${{ github.workspace }}
          ls -la ${{ github.workspace }}/DEBIAN
          ls -la ${{ github.workspace }}/scripts
          ls -la ${{ github.workspace }}/custom_files

      - name: Create .deb File
        run: dpkg-deb --build .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-deb-file
          path: ./*.deb