name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:      
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t createpackage -f createPackage.Dockerfile .

      - name: Run Docker Image
        run: docker run -v $(pwd)/../DEBUG:/app/DEBUG createpackage

      - name: List files
        run: ls -la $(pwd)/../DEBUG

      - name: Create .deb file
        run: dpkg-deb --build $(pwd)/../DEBUG $(pwd)/../

      - name: Upload .deb file
        uses: actions/upload-artifact@v4
        with:
          name: my-deb-file
          path: $(pwd)/../